### ISSUE TITLE
Template fails with missing X-Hub-Signiture

### ISSUE THREAD

**Issue by MarshallOfSound** [probot/plugin-template#8]
Steps to reproduce:

1. Cloned this repository  
2. Set up a new Integration on GitHub  
3. Provided credentials to plugin template and ran "npm start"  
4. Set up an ngrok tunnel on port 3000
5. Installed the integration on a repository

```
$ probot run ./index.js
Yay, the plugin was loaded!
Listening on http://localhost:3000
13:16:34.530Z ERROR PRobot: No X-Hub-Signature found on request
  Error: No X-Hub-Signature found on request
      at hasError (C:\Users\Samuel\projects\plugin-template\node_modules\github-webhook-handler\github-webhook-handler.js:46:17)
      at handler (C:\Users\Samuel\projects\plugin-template\node_modules\github-webhook-handler\github-webhook-handler.js:57:14)
      at Server.http.createServer (C:\Users\Samuel\projects\plugin-template\node_modules\probot\lib\server.js:5:5)
      at emitTwo (events.js:106:13)
      at Server.emit (events.js:194:7)
      at parserOnIncoming (_http_server.js:565:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
Error: No X-Hub-Signature found on request
    at hasError (C:\Users\Samuel\projects\plugin-template\node_modules\github-webhook-handler\github-webhook-handler.js:46:17)
    at handler (C:\Users\Samuel\projects\plugin-template\node_modules\github-webhook-handler\github-webhook-handler.js:57:14)
    at Server.http.createServer (C:\Users\Samuel\projects\plugin-template\node_modules\probot\lib\server.js:5:5)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:194:7)
    at parserOnIncoming (_http_server.js:565:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

Not sure if this is ngroks fault or something else, but I saw ngrok recommended somewhere in the probot docs so I assume I'm just doing something wrong 😆

**Comment by bkeepers** [comment]
Hey @MarshallOfSound, this is actually coming from the webhook handler, and means that the "webhook secret" configured on GitHub doesn't match the one configured locally. See step 4 of https://github.com/probot/probot/blob/master/docs/development.md

<img width="788" alt="integrations_-_owners" src="https://cloud.githubusercontent.com/assets/173/24322551/59356484-1134-11e7-81d4-bec6de9cd72a.png">

**Comment by MarshallOfSound** [comment]
RIP, knew I was missing something. Cheers @bkeepers 

Now to make some cool bots 😆

**Comment by MarshallOfSound** [comment]
@bkeepers Damm, this is pretty awesome 👍 

https://github.com/MarshallOfSound/probot-test/issues/11

Automatic issue duplicate detection 😄

**Comment by bkeepers** [comment]
@MarshallOfSound WOAH, that's awesome!  I ❤️ it so much.  I'd love to have that be a plugin available under the @probot org, so let me know when you have it to a state that you're comfortable sharing it.

**Comment by MarshallOfSound** [comment]
@bkeepers The source code is available here: https://github.com/MarshallOfSound/probot-issue-duplicate-detection

I've got it deployed to now and running on some of my repositories already 😄 

https://duplicate.probot.samuelattard.us

I can add you as a collaborator and you can move it where you want 👍
